name: Setup build
description: "Setup build(docker login, get code, create builder)"
inputs:
  docker-user:
    description: "Docker user"
    required: true
  docker-password:
    description: "Docker password"
    required: true
runs:
  using: composite
  steps:
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.docker-user }}
        password: ${{ inputs.docker-password }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        version: "lab:latest"
        driver: cloud
        endpoint: "dzhuryn/cloud-builder"
        install: true
